version: '1.0'

services:

  frontend:
    build:
      context: frontend
    volumes:
      - frontend-node-modules:/app/node_modules
      - ./frontend/src:/app/src
    depends_on:
      - backend
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - react-express

  backend:
    build:
      context: backend
    volumes:
      - backend-node-modules:/app/node_modules
      - ./backend/src:/app/src
    command: npm run devStart
    depends_on:
      - mongo
    env_file: ./backend/docker.env
    networks:
      - express-mongo
      - react-express
    expose:
      - 8080

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

networks:
  react-express:
  express-mongo:

volumes:
  mongo-data:
  backend-node-modules:
  frontend-node-modules: